// Please do not edit this file.
//
// The purpose of this file is to make sure that the TypeScript compiler
// understands that .vue files are legitimate TypeScript modules.  You need this
// file, but you don't need to understand it.
declare module "*.vue" {
    import Vue from "vue";
    export default Vue;
}